import {
  CalendarDays,
  Car,
  CheckSquare,
  CircleDot,
  FileText,
  House,
  Inbox,
  MessageSquare,
  Search,
  Settings,
  Wallet,
  Zap,
} from "lucide-react";

import type { CommandItem } from "@/lib/commands/types";

export const routeCommands: readonly CommandItem[] = [
  {
    id: "route-dashboard",
    title: "Go to Dashboard",
    subtitle: "/",
    keywords: ["home", "overview"],
    group: "Navigation",
    icon: House,
    action: { type: "navigate", href: "/" },
    metadata: { priority: "secondary", recentLabel: "Open Dashboard" },
  },
  {
    id: "route-today",
    title: "Open Today",
    subtitle: "Daily focus and briefing",
    keywords: ["daily", "plan", "focus", "go to today"],
    group: "Capture",
    icon: CalendarDays,
    action: { type: "navigate", href: "/today" },
    metadata: { priority: "primary", contextualScore: 80 },
  },
  {
    id: "route-inbox",
    title: "Open Inbox",
    subtitle: "Drop anything into Archflow",
    keywords: ["capture", "quick capture", "go to inbox"],
    group: "Capture",
    icon: Inbox,
    action: { type: "navigate", href: "/inbox" },
    metadata: { priority: "primary", contextualScore: 95 },
  },
  {
    id: "route-search",
    title: "Open Search",
    subtitle: "Find tasks, notes, activity, and memory",
    keywords: ["find", "global search", "go to search"],
    group: "Search",
    icon: Search,
    action: { type: "navigate", href: "/search" },
    metadata: { priority: "primary", contextualScore: 85 },
  },
  {
    id: "route-timeline",
    title: "Open Timeline",
    subtitle: "Review recent context and activity",
    keywords: ["activity", "history", "events", "go to timeline"],
    group: "Search",
    icon: CircleDot,
    action: { type: "navigate", href: "/timeline" },
    metadata: { priority: "primary", contextualScore: 75 },
  },
  {
    id: "route-tasks",
    title: "Go to Tasks",
    subtitle: "/tasks",
    keywords: ["todos", "work"],
    group: "Navigation",
    icon: CheckSquare,
    action: { type: "navigate", href: "/tasks" },
    metadata: { priority: "normal", recentLabel: "Open Tasks" },
  },
  {
    id: "route-notes",
    title: "Go to Notes",
    subtitle: "/notes",
    keywords: ["knowledge", "ideas"],
    group: "Navigation",
    icon: FileText,
    action: { type: "navigate", href: "/notes" },
    metadata: { priority: "normal", recentLabel: "Open Notes" },
  },
  {
    id: "route-ai-chat",
    title: "Go to AI Chat",
    subtitle: "/ai-chat",
    keywords: ["assistant", "chat"],
    group: "AI",
    icon: MessageSquare,
    action: { type: "navigate", href: "/ai-chat" },
    metadata: { priority: "secondary", recentLabel: "Open AI Chat" },
  },
  {
    id: "route-finance",
    title: "Go to Finance",
    subtitle: "/finance",
    keywords: ["money", "transactions", "cashflow"],
    group: "Navigation",
    icon: Wallet,
    action: { type: "navigate", href: "/finance" },
    metadata: { priority: "secondary", recentLabel: "Open Finance" },
  },
  {
    id: "route-cars",
    title: "Go to Cars",
    subtitle: "/cars",
    keywords: ["vehicles", "maintenance"],
    group: "Navigation",
    icon: Car,
    action: { type: "navigate", href: "/cars" },
    metadata: { priority: "secondary", recentLabel: "Open Cars" },
  },
  {
    id: "route-automation",
    title: "Go to Automation",
    subtitle: "/automation",
    keywords: ["workflows", "telegram", "reminders"],
    group: "Navigation",
    icon: Zap,
    action: { type: "navigate", href: "/automation" },
    metadata: { priority: "secondary", recentLabel: "Open Automation" },
  },
  {
    id: "route-settings",
    title: "Go to Settings",
    subtitle: "/settings",
    keywords: ["preferences", "appearance", "profile"],
    group: "Navigation",
    icon: Settings,
    action: { type: "navigate", href: "/settings" },
    metadata: { priority: "secondary", recentLabel: "Open Settings" },
  },
];
