import {
  CalendarDays,
  Car,
  CheckSquare,
  FileText,
  House,
  Inbox,
  MessageSquare,
  Search,
  Settings,
  Wallet,
  Zap,
} from "lucide-react";

import type { CommandItem } from "@/lib/commands/types";

export const routeCommands: readonly CommandItem[] = [
  {
    id: "route-dashboard",
    title: "Go to Dashboard",
    subtitle: "/",
    keywords: ["home", "overview"],
    group: "Navigate",
    icon: House,
    action: { type: "navigate", href: "/" },
  },
  {
    id: "route-today",
    title: "Go to Today",
    subtitle: "/today",
    keywords: ["daily", "plan", "focus"],
    group: "Navigate",
    icon: CalendarDays,
    action: { type: "navigate", href: "/today" },
  },
  {
    id: "route-inbox",
    title: "Go to Inbox",
    subtitle: "/inbox",
    keywords: ["capture", "quick capture"],
    group: "Navigate",
    icon: Inbox,
    action: { type: "navigate", href: "/inbox" },
  },
  {
    id: "route-search",
    title: "Go to Search",
    subtitle: "/search",
    keywords: ["find", "global search"],
    group: "Navigate",
    icon: Search,
    action: { type: "navigate", href: "/search" },
  },
  {
    id: "route-tasks",
    title: "Go to Tasks",
    subtitle: "/tasks",
    keywords: ["todos", "work"],
    group: "Navigate",
    icon: CheckSquare,
    action: { type: "navigate", href: "/tasks" },
  },
  {
    id: "route-notes",
    title: "Go to Notes",
    subtitle: "/notes",
    keywords: ["knowledge", "ideas"],
    group: "Navigate",
    icon: FileText,
    action: { type: "navigate", href: "/notes" },
  },
  {
    id: "route-ai-chat",
    title: "Go to AI Chat",
    subtitle: "/ai-chat",
    keywords: ["assistant", "chat"],
    group: "Navigate",
    icon: MessageSquare,
    action: { type: "navigate", href: "/ai-chat" },
  },
  {
    id: "route-finance",
    title: "Go to Finance",
    subtitle: "/finance",
    keywords: ["money", "transactions", "cashflow"],
    group: "Navigate",
    icon: Wallet,
    action: { type: "navigate", href: "/finance" },
  },
  {
    id: "route-cars",
    title: "Go to Cars",
    subtitle: "/cars",
    keywords: ["vehicles", "maintenance"],
    group: "Navigate",
    icon: Car,
    action: { type: "navigate", href: "/cars" },
  },
  {
    id: "route-automation",
    title: "Go to Automation",
    subtitle: "/automation",
    keywords: ["workflows", "telegram", "reminders"],
    group: "Navigate",
    icon: Zap,
    action: { type: "navigate", href: "/automation" },
  },
  {
    id: "route-settings",
    title: "Go to Settings",
    subtitle: "/settings",
    keywords: ["preferences", "appearance", "profile"],
    group: "Navigate",
    icon: Settings,
    action: { type: "navigate", href: "/settings" },
  },
];
